name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go mod download

      - name: Build Executable
        run: go build cmd/json2go/main.go

      - name: Run unit tests
        run: go test ./... --cover
